import { describe, it, expect } from 'vitest';
import request from 'supertest';
import { createApp } from '../src/app';
import { generateToken } from '../src/utils/jwt';

const app = createApp();

const generateTestToken = () => {
  return generateToken({
    userId: 'user_test_git_123',
    email: 'git-tester@devforge.ai',
    role: 'developer',
  });
};

describe('Phase 7 — Isolated Git & Continuous Delivery API Layer', () => {
  it('GET /api/projects/:id/git/branches without token should return 401 unauthorized', async () => {
    const res = await request(app).get('/api/projects/proj_sample_01/git/branches');
    expect(res.status).toBe(401);
    expect(res.body.success).toBe(false);
  });

  it('GET /api/projects/:id/git/branches with token should return active isolated task branches', async () => {
    const token = generateTestToken();
    const res = await request(app)
      .get('/api/projects/proj_sample_01/git/branches')
      .set('Authorization', `Bearer ${token}`);

    expect(res.status).toBe(200);
    expect(res.body.success).toBe(true);
    expect(Array.isArray(res.body.data)).toBe(true);
    expect(res.body.data.length).toBeGreaterThan(0);
    expect(res.body.data[0].name).toContain('devforge/task/');
  });

  it('POST /api/projects/:id/git/branches should create new isolated task branch', async () => {
    const token = generateTestToken();
    const res = await request(app)
      .post('/api/projects/proj_sample_01/git/branches')
      .set('Authorization', `Bearer ${token}`)
      .send({
        name: 'security-hardening',
        baseBranch: 'main',
        commitMessage: 'fix(sec): sanitize auth token headers',
      });

    expect(res.status).toBe(201);
    expect(res.body.success).toBe(true);
    expect(res.body.data.name).toBe('devforge/task/security-hardening');
    expect(res.body.data.status).toBe('active');
  });

  it('POST /api/projects/:id/git/pull-requests should generate GitHub Pull Request', async () => {
    const token = generateTestToken();
    const res = await request(app)
      .post('/api/projects/proj_sample_01/git/pull-requests')
      .set('Authorization', `Bearer ${token}`)
      .send({
        title: 'feat(sec): Automated Security Hardening Patch',
        body: 'Pull request generated by DevForge AI for branch devforge/task/security-hardening.',
        sourceBranch: 'devforge/task/security-hardening',
        targetBranch: 'main',
      });

    expect(res.status).toBe(201);
    expect(res.body.success).toBe(true);
    expect(res.body.data.prId).toBeDefined();
    expect(res.body.data.prNumber).toBeGreaterThan(0);
    expect(res.body.data.status).toBe('open');
    expect(res.body.data.htmlUrl).toContain('/pull/');
  });

  it('GET /api/projects/:id/git/pipelines should return continuous delivery triggers', async () => {
    const token = generateTestToken();
    const res = await request(app)
      .get('/api/projects/proj_sample_01/git/pipelines')
      .set('Authorization', `Bearer ${token}`);

    expect(res.status).toBe(200);
    expect(res.body.success).toBe(true);
    expect(Array.isArray(res.body.data)).toBe(true);
    expect(res.body.data[0].environment).toBeDefined();
  });

  it('POST /api/projects/:id/git/pipelines/trigger should trigger delivery pipeline build', async () => {
    const token = generateTestToken();
    const res = await request(app)
      .post('/api/projects/proj_sample_01/git/pipelines/trigger')
      .set('Authorization', `Bearer ${token}`)
      .send({
        branch: 'devforge/task/security-hardening',
        environment: 'staging',
      });

    expect(res.status).toBe(201);
    expect(res.body.success).toBe(true);
    expect(res.body.data.status).toBe('success');
    expect(res.body.data.environment).toBe('staging');
    expect(res.body.data.deployedUrl).toContain('devforge-deploy.app');
  });
});
