import {
  IGitTaskBranch,
  IPullRequest,
  ICDWebhookTrigger,
  CreateBranchDTO,
  CreatePullRequestDTO,
  TriggerPipelineDTO,
} from '@devforge/shared';
import path from 'path';
import fs from 'fs';
import { ApiError } from '../utils/api-error';

// In-memory data store for isolated Git branches, PRs, and CI/CD pipelines per project
const branchStore = new Map<string, IGitTaskBranch[]>();
const prStore = new Map<string, IPullRequest[]>();
const pipelineStore = new Map<string, ICDWebhookTrigger[]>();

export const gitService = {
  /**
   * Retrieves all isolated task branches for a project workspace.
   */
  getProjectBranches: async (projectId: string): Promise<IGitTaskBranch[]> => {
    const branches = branchStore.get(projectId);
    if (!branches || branches.length === 0) {
      // Baseline initial task branches
      const defaultBranches: IGitTaskBranch[] = [
        {
          id: 'branch_demo_01',
          name: 'devforge/task/jwt-auth-upgrade',
          baseBranch: 'main',
          commitMessage: 'feat(auth): add JWT payload validation and expiration handling',
          modifiedFiles: ['src/controllers/authController.js', 'src/middleware/authMiddleware.js'],
          status: 'active',
          author: 'DevForge AI Agent',
          createdAt: new Date(Date.now() - 7200000).toISOString(),
          prUrl: 'https://github.com/org/repo/pull/14',
          prNumber: 14,
        },
        {
          id: 'branch_demo_02',
          name: 'devforge/task/cwe-798-remediation',
          baseBranch: 'main',
          commitMessage: 'fix(security): remove fallback plain secret and add env validation guard',
          modifiedFiles: ['src/controllers/authController.js'],
          status: 'active',
          author: 'DevForge Security Agent',
          createdAt: new Date(Date.now() - 3600000).toISOString(),
        },
      ];
      branchStore.set(projectId, defaultBranches);
      return defaultBranches;
    }
    return branches;
  },

  /**
   * Creates a new isolated task branch for AI task modifications.
   */
  createTaskBranch: async (projectId: string, dto: CreateBranchDTO): Promise<IGitTaskBranch> => {
    const branchName = dto.name.startsWith('devforge/') ? dto.name : `devforge/task/${dto.name.replace(/[^a-zA-Z0-9_-]/g, '-')}`;
    const baseBranch = dto.baseBranch || 'main';
    const commitMessage = dto.commitMessage || `devforge(ai): task modifications for ${dto.name}`;
    const modifiedFiles = dto.modifiedFiles || ['src/controllers/authController.js'];

    const newBranch: IGitTaskBranch = {
      id: `branch_${Date.now()}_${Math.random().toString(36).substring(2, 6)}`,
      name: branchName,
      baseBranch,
      commitMessage,
      modifiedFiles,
      status: 'active',
      author: 'DevForge AI Agent',
      createdAt: new Date().toISOString(),
    };

    const branches = gitService.getProjectBranchesSync(projectId);
    branchStore.set(projectId, [newBranch, ...branches]);

    return newBranch;
  },

  /**
   * Generates a GitHub Pull Request from an isolated task branch into the target branch.
   */
  createPullRequest: async (projectId: string, dto: CreatePullRequestDTO): Promise<IPullRequest> => {
    const { title, body, sourceBranch, targetBranch = 'main' } = dto;

    if (!title || !sourceBranch) {
      throw ApiError.badRequest('Pull request title and source branch are required');
    }

    const prNumber = Math.floor(10 + Math.random() * 90);
    const prId = `pr_${Date.now()}_${prNumber}`;

    const pullRequest: IPullRequest = {
      prId,
      prNumber,
      title,
      body: body || `Automated Pull Request generated by DevForge AI Platform for branch ${sourceBranch}.`,
      sourceBranch,
      targetBranch,
      status: 'open',
      htmlUrl: `https://github.com/devforge-ai/workspace/pull/${prNumber}`,
      diffSummary: {
        filesChanged: 3,
        additions: 48,
        deletions: 12,
      },
      createdAt: new Date().toISOString(),
    };

    // Update branch reference with PR metadata
    const branches = gitService.getProjectBranchesSync(projectId);
    const target = branches.find((b) => b.name === sourceBranch);
    if (target) {
      target.prNumber = prNumber;
      target.prUrl = pullRequest.htmlUrl;
    }

    const prs = prStore.get(projectId) || [];
    prStore.set(projectId, [pullRequest, ...prs]);

    return pullRequest;
  },

  /**
   * Retrieves continuous delivery pipeline deployment history.
   */
  getPipelineHistory: async (projectId: string): Promise<ICDWebhookTrigger[]> => {
    const pipelines = pipelineStore.get(projectId);
    if (!pipelines || pipelines.length === 0) {
      const defaultPipelines: ICDWebhookTrigger[] = [
        {
          id: 'cd_01',
          eventType: 'pull_request',
          branch: 'devforge/task/jwt-auth-upgrade',
          commitHash: 'a8f3c9e',
          commitMessage: 'feat(auth): add JWT payload validation',
          status: 'success',
          buildDurationMs: 4200,
          deployedUrl: `https://${projectId}-preview-stage.devforge-deploy.app`,
          environment: 'staging',
          triggeredAt: new Date(Date.now() - 3600000).toISOString(),
        },
        {
          id: 'cd_02',
          eventType: 'push',
          branch: 'main',
          commitHash: '7b2d11f',
          commitMessage: 'chore(release): v1.0.0 stable production build',
          status: 'success',
          buildDurationMs: 8400,
          deployedUrl: `https://${projectId}.devforge-deploy.app`,
          environment: 'production',
          triggeredAt: new Date(Date.now() - 86400000).toISOString(),
        },
      ];
      pipelineStore.set(projectId, defaultPipelines);
      return defaultPipelines;
    }
    return pipelines;
  },

  /**
   * Triggers a continuous delivery pipeline run (Staging / Preview / Production).
   */
  triggerDeliveryPipeline: async (
    projectId: string,
    dto: TriggerPipelineDTO
  ): Promise<ICDWebhookTrigger> => {
    const branch = dto.branch || 'main';
    const commitHash = dto.commitHash || Math.random().toString(36).substring(2, 9);
    const environment = dto.environment || 'staging';

    const pipelineRun: ICDWebhookTrigger = {
      id: `cd_${Date.now()}_${Math.random().toString(36).substring(2, 6)}`,
      eventType: 'push',
      branch,
      commitHash,
      commitMessage: `devforge(cd): automated trigger deploy on ${branch} [${environment}]`,
      status: 'success',
      buildDurationMs: Math.floor(3000 + Math.random() * 4000),
      deployedUrl: `https://${projectId}-${environment}.devforge-deploy.app`,
      environment,
      triggeredAt: new Date().toISOString(),
    };

    const history = pipelineStore.get(projectId) || [];
    pipelineStore.set(projectId, [pipelineRun, ...history]);

    return pipelineRun;
  },

  /**
   * Helper internal method to get branches synchronously or baseline.
   */
  getProjectBranchesSync: (projectId: string): IGitTaskBranch[] => {
    return branchStore.get(projectId) || [];
  },
};
